version: '3.8'

services:
  frontend:
    build: ./my-app
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb+srv://maryamtahir061:meenuu123@clusterweb.l6zg4.mongodb.net/
      - PORT=5000
    volumes:
      - ./server:/app
